### ISSUE TITLE
Tela de login não é configurável

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-api#1]
De acordo com a documentação, o botão de login da aplicação deveria ser configurável via arquivo de configuração.
_**"O ícone e o rótulo do botão de login da interface (abaixo) também serão definidos na instalação via arquivo de configuração."**_
https://totemti.atlassian.net/wiki/spaces/OPMO/pages/1046478905/Login+1.0

**Comment by vrcristo1980** [comment]
Item corrigido

**Comment by vdcordeiro** [comment]
Corrigido
