### ISSUE TITLE
Relacionamento IS_ROOT_OF aplicado indevidamente

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-api#2]
Na criação e utilização de um domínio, o relacionamento IS_ROOT_OF está sendo aplicado indevidamente no banco.
Conforme o diagrama de classes, somente a entidade Locality deveria ter o relacionamento IS_ROOT_OF com Domain, mesmo assim, somente a primeira Locality teria esse relacionamento. Além disso, há uma cardinalidade 1 para 1 nessa relação. Isso foi feito propositalmente para garantir que haja uma única localidade raiz para cada domínio. Assim, na interface, para selecionar o domínio todo, basta selecionar essa localidade raiz.

Note, que há uma diferença sutil entre: 
- [selecionar todos os municípios do Estado individualmente] e 
- [selecionar o Estado]. 
Algumas entregas são administrativas e beneficiam o Estado como um todo (ex.: o próprio Open PMO). O benefício aos municípios é muito indireto e não é relevante para eles. Não deve nem aparecer num relatório de entregas que beneficiam um determinado município. Já um "Programa de restauração de toda a malha rodoviária do Estado" é significativo e mensurável para cada um dos 78 municípios do Estado e deve aparecer no mesmo relatório, pois um prefeito reconhecerá o valor, quando dissermos que o Estado está beneficiando o seu município com esse programa.

Diagrama de Classes:
![image](https://user-images.githubusercontent.com/41954965/108891631-b340cf00-75ed-11eb-85c9-4451d7e5debd.png)

Banco de Dados:
![image](https://user-images.githubusercontent.com/41954965/108905367-65809280-75fe-11eb-9afc-306e59e8dc11.png)

Observar ainda que na release de correção dessa issue deve ser executada uma correção do banco de dados de homologação existente, ou a limpeza e reinício do bd do zero.

**Comment by vrcristo1980** [comment]
Olá Vagner, bom dia! 

Na questão do domínio, tanto na documentação quanto no modelo haviam
pontos e regras que não estavam suficientemente detalhados. Por exemplo,
não estava claro o relacionamento entre domain e office e tampouco entre
domain e property model. Também não definimos regras como por exemplo:
uma localidade pode ser reaproveitada em outro domain ou deve ser
duplicada no banco?  

Proponho que esse item seja incluído como alteração dentro do escopo da
release 2. 

Att,  

Vanessa Reis Cristo 

Consultora - Totem TI 

vanessa.cristo@totemti.com.br 

Celular: +55 61 99831 1208 

Em 23/02/2021 17:46, Vagner Dargan Cordeiro escreveu:

> Na criação e utilização de um domínio, o relacionamento IS_ROOT_OF está sendo aplicado indevidamente no banco.
> Conforme o diagrama de classes, somente a entidade Locality deveria ter o relacionamento IS_ROOT_OF com Domain, mesmo assim, somente a primeira Locality teria esse relacionamento. Além disso, há uma cardinalidade 1 para 1 nessa relação. Isso foi feito propositalmente para garantir que haja uma única localidade raiz para cada domínio. Assim, na interface, para selecionar o domínio todo, basta selecionar essa localidade raiz. 
> 
> Note, que há uma diferença sutil entre: 
> 
> * [selecionar todos os municípios do Estado individualmente] e
> 
> * [selecionar o Estado].
> Algumas entregas são administrativas e beneficiam o Estado como um todo (ex.: o próprio Open PMO). O benefício aos municípios é muito indireto e não é relevante para eles. Não deve nem aparecer num relatório de entregas que beneficiam um determinado município. Já um "Programa de restauração de toda a malha rodoviária do Estado" é significativo e mensurável para cada um dos 78 municípios do Estado e deve aparecer no mesmo relatório, pois um prefeito reconhecerá o valor, quando dissermos que o Estado está beneficiando o seu município com esse programa. 
> 
> Diagrama de Classes:
> [1] 
> 
> Banco de Dados:
> [2] 
> 
> Observar ainda que na release de correção dessa issue deve ser executada uma correção do banco de dados de homologação existente, ou a limpeza e reinício do bd do zero. 
> 
> --
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
 

Links:
------
[1]
https://user-images.githubusercontent.com/41954965/108891631-b340cf00-75ed-11eb-85c9-4451d7e5debd.png
[2]
https://user-images.githubusercontent.com/41954965/108905367-65809280-75fe-11eb-9afc-306e59e8dc11.png
[3] https://github.com/sep-es-br/openpmo-api/issues/2
[4]

**Comment by vdcordeiro** [comment]
Bom dia Vanessa, 
Como já disse outras vezes, precisamos ter cuidado ao transferir implementações deste ciclo para o seguinte. Me preocupa ainda mais quando se trata de erros conceituais. O próximo ciclo já está bem inchado e neste caso discordo de você: 
  
- "não estava claro o relacionamento entre domain e office" 
>> Entendo que está absolutamente claro no protótipo e documentação que um domínio é criado para um escritório específico, uma vez que na interface isso é feito a partir do menu do escritório (a exemplo dos demais cadastros: organizações, estratégias, unidades de medida, permissões). Além disso, o usuário comum precisa ter permissão de editor naquele escritório específico. 
  
-  "...e tampouco entre domain e property model..." 
>> Está claro no protótipo e documentação que no property model do tipo "Locality Selection" há a possibilidade de se vincular uma "locality" para o metadado "default value". Também há na mesma "property model" a seleção de um domínio para indicar as localities passíveis de seleção. O objetivo final é estabelecer a relação entre locality e property model no banco. Uma relação entre domain e o property model não é essencial, pois pode-se chegar ao domain a partir da locality selecionada. No entanto, por uma decisão de projeto, não haveria problema algum em adicionar um relacionamento entre domain e property model para facilitar as consultas e a compreensão do modelo, mas o relacionamento deve ter um nome que comunique claramente o objetivo daquela relação. "IS_ROOT_OF" não comunica isso.  
  
- "Também não definimos regras como por exemplo: uma localidade pode ser reaproveitada em outro domain ou deve ser 
duplicada no banco?" 
>> Na verdade definimos a regra quando decidimos não adicionar nenhuma indicação para o reaproveitamento no protótipo nem na documentação... e a equipe entendeu, pois não implementou o recurso. O reuso de elementos entre dois cadastros é um recurso adicional. Temos que especificar e documentar apenas nos casos onde o recurso é requerido. Da mesma forma, não temos reaproveitamento de workpack ou de plano entre escritórios no ciclo 1. Para contemplar isso no ciclo 2, adicionamos a funcionalidade no protótipo e na documentação. Conforme nossa documentação, não teremos reuso de localidades entre domínios nem mesmo no ciclo 2. 
  
Concluindo, no caso do relacionamento (PropertyModel)-[IS_ROOT_OF]->(Domain), podemos manter um relacionamento, mas encontrem um nome melhor, pois "Modelo de Propriedade" não é raiz do "Domínio", como o atual nome sugere.  
  
Com relação à cardinalidade 1 para 1 entre domain e locality, isso não ficou refletido na documentação e protótipo, então concordo seja mantida a possibilidade de criar múltiplas localidades no primeiro nível do domínio. Já os relacionamentos (Locality)-[IS_ROOT_OF]->(Domain) para as localidades a partir do segundo nível devem ser excluídos, como apontado na issue, pois essas não são raízes do domínio. Somente as do primeiro nível.  
  
P.S.: Acabo de perceber agora que o mesmo erro conceitual descrito no parágrafo acima se repete nas outras entidades com relações recursivas/hierárquicas:
- (WorkpackModel)-[IS_ROOT_OF]->(PlanModel); 
- (Workpack)-[IS_ROOT_OF]->(Plan); 
  
   
   
 
 
Vagner Cordeiro | Coordenador Geral de TI | SEP 
GOVERNO DO ESPÍRITO SANTO | (27) 3636-4293 (27) 98837-0929   

   

-----mensagem original-----

De: vrcristo1980 <notifications@github.com>
Para: sep-es-br <openpmo-api@noreply.github.com>
Cc: Vagner <vagner.cordeiro@planejamento.es.gov.br>; Author <author@noreply.github.com>
Encontro: quarta-feira, 24 de fevereiro de 2021 às 09:23 -03
Sujeito: Re: [sep-es-br/openpmo-api] Relacionamento IS_ROOT_OF aplicado indevidamente (#2)

 

  Olá Vagner, bom dia! 

Na questão do domínio, tanto na documentação quanto no modelo haviam
pontos e regras que não estavam suficientemente detalhados. Por exemplo,
não estava claro o relacionamento entre domain e office e tampouco entre
domain e property model. Também não definimos regras como por exemplo:
uma localidade pode ser reaproveitada em outro domain ou deve ser
duplicada no banco? 

Proponho que esse item seja incluído como alteração dentro do escopo da
release 2. 

Att, 

Vanessa Reis Cristo 

Consultora - Totem TI 

vanessa.cristo@totemti.com.br 

Celular: +55 61 99831 1208 

Em 23/02/2021 17:46, Vagner Dargan Cordeiro escreveu:

> Na criação e utilização de um domínio, o relacionamento IS_ROOT_OF está sendo aplicado indevidamente no banco.
> Conforme o diagrama de classes, somente a entidade Locality deveria ter o relacionamento IS_ROOT_OF com Domain, mesmo assim, somente a primeira Locality teria esse relacionamento. Além disso, há uma cardinalidade 1 para 1 nessa relação. Isso foi feito propositalmente para garantir que haja uma única localidade raiz para cada domínio. Assim, na interface, para selecionar o domínio todo, basta selecionar essa localidade raiz. 
> 
> Note, que há uma diferença sutil entre: 
> 
> * [selecionar todos os municípios do Estado individualmente] e
> 
> * [selecionar o Estado].
> Algumas entregas são administrativas e beneficiam o Estado como um todo (ex.: o próprio Open PMO). O benefício aos municípios é muito indireto e não é relevante para eles. Não deve nem aparecer num relatório de entregas que beneficiam um determinado município. Já um "Programa de restauração de toda a malha rodoviária do Estado" é significativo e mensurável para cada um dos 78 municípios do Estado e deve aparecer no mesmo relatório, pois um prefeito reconhecerá o valor, quando dissermos que o Estado está beneficiando o seu município com esse programa. 
> 
> Diagrama de Classes:
> [1] 
> 
> Banco de Dados:
> [2] 
> 
> Observar ainda que na release de correção dessa issue deve ser executada uma correção do banco de dados de homologação existente, ou a limpeza e reinício do bd do zero. 
> 
> --
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].


Links:
------
[1]
https://user-images.githubusercontent.com/41954965/108891631-b340cf00-75ed-11eb-85c9-4451d7e5debd.png
[2]
https://user-images.githubusercontent.com/41954965/108905367-65809280-75fe-11eb-9afc-306e59e8dc11.png
[3] https://imsva91-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fsep%2des%2dbr%2fopenpmo%2dapi%2fissues%2f2&umid=1BCBCAF4-BC16-1405-B261-49206DBFAA41&auth=8a8c08660fd98a755cd0b95645c09d68a33dce39-eef85c3938b426160a9bd873148b677fb714e347
[4]
https://imsva91-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2dauth%2fAREF4UPMACNXQD7QW2JCNRTTAQH3PANCNFSM4YDF7X6A&umid=1BCBCAF4-BC16-1405-B261-49206DBFAA41&auth=8a8c08660fd98a755cd0b95645c09d68a33dce39-e28e7bd628b203c2d1fa5971b9a6297810b58b3e —

**Comment by vrcristo1980** [comment]
item corrigido

**Comment by vdcordeiro** [comment]
Corrigido
